os: linux
dist: bionic

services: docker

before_install:
  - cd elasticsearch

script:
- echo "$CCR_PASSWORD" | docker login -u "$CCR_USERNAME" ccr.ccs.tencentyun.com --password-stdin
- docker build -t wajika/elasticsearch:$(date +%Y.%m.%d) .
- docker push wajika/elasticsearch:$(date +%Y.%m.%d)
