name: Docker Image CI

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file elasticsearch/Dockerfile --tag elasticsearch:$(date +%s)
      working-directory: ./elasticsearch
    
